<?php

namespace IPG\EventsBundle\Entity;

use Doctrine\ORM\ORMInvalidArgumentException;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    /**
     * @param array $criteria array of field name and it's value that should be searched
     * @return array|ORMInvalidArgumentException
     */
    public function findLike($criteria = array())
    {
        if (!is_array($criteria)) {
            return new ORMInvalidArgumentException('Criteria mus be array');
        }

        list($fieldName, $fieldValue) = $criteria;

        return $this->getEntityManager()
                ->createQuery("
                    SELECT c.".$fieldName."
                        FROM IPGEventsBundle:Category c
                        WHERE c.".$fieldName."
                            LIKE '%".$fieldValue."%'
                ")
                ->getResult();
    }
}
