<?php

namespace IPG\EventsBundle\Entity;

use Doctrine\ORM\ORMInvalidArgumentException;
use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    /**
     * @param array $criteria array of field name and it's value that should be searched
     * @return array|ORMInvalidArgumentException
     */
    public function getId($criteria = array())
    {
        if (!is_array($criteria)) {
            return new ORMInvalidArgumentException('Criteria mus be array');
        }

        list($fieldName, $fieldValue) = $criteria;

        return $this->getEntityManager()
                ->createQuery("
                    SELECT l.id
                        FROM IPGEventsBundle:Location l
                        WHERE l.".$fieldName."
                            LIKE '%".$fieldValue."%'
                ")
                ->getResult();
    }
}
